apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - protocol: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30500
    - protocol: management
      port: 15672
      targetPort: 15672
      nodePort: 30501
